version: '3.8'
services:
  movies:
    image: gopaldocker1974/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: gopaldocker1974/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: gopaldocker1974/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: gopaldocker1974/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

